language: python

cache: pip

# https://docs.travis-ci.com/user/build-stages/

#branches:
#  only:
#  - master      # Build if the branch is the master branch

# Matrix Expansion (python versions and databases to run tox tests against)
# Tox is only used for running the tests, the linters only have to run against the latest code
python:
  - '3.8'
  - '3.7'
  - '3.6'

env:
- DJANGO_DB=SQLITE
- DJANGO_DB=POSTGRES

jobs:
  include:
    - name: 'Linting and Checks'
      services: echo PHASE - "services" (nothing to do)
      install:
      # don't use the '--upgrade' to not upgrade pinned requirements with generic ones
      - pip install -r requirements.txt
      - pip list
      script:
      # Check Django, e.g. Migrations are working
      - ./dev/check_django.sh

      # Run Linter
      - ./dev/run_linters.sh

      # Run Package Safety
      - ./dev/check_package_safety.sh

services:
- postgresql

before_install:
# Print Python Details, Upgrade base packages
- pip --version

- python --version --version
- pip list

- python -m pip install --upgrade pip pipenv
- pip list

# Print Environment Variables
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then set; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then printenv; fi

install:
  pip install tox-travis

before_script:
- if [ "$DJANGO_DB" = "POSTGRES" ]; then psql -c 'create database travis_ci_test;' -U postgres; fi

script:
- if [ "$DJANGO_DB" = "SQLITE" ]; then
    tox sqlite;
  elif [ "$DJANGO_DB" = "POSTGRES" ]; then
    tox postgres-travis;
  fi
  else
    echo Unexpected DJANGO_DB variable "$DJANGO_DB", error
    exit 1
  fi

after_success:
- codecov
