language: python

cache: pip

# TODO
# Create athe Same Travis with Build Stages, so only deploy if build ok on all jobs
# https://docs.travis-ci.com/user/build-stages/

# Limit under which Conditions we run Travis
branches:
  only:
  - master      # Build if the branch is the master branch

matrix:
  include:
  - name: "Linux, Python 3.6"
    os: linux
    dist: xenial
    python: "3.6"
  - name: "Linux, Python 3.7"
    os: linux
    dist: xenial
    python: "3.7"
  - name: "Linux, Python 3.8"
    os: linux
    dist: xenial
    python: "3.8"

install:
- python --version --version
- pip list

- python -m pip install --upgrade pip pipenv setuptools wheel
- pip list

# don't use the '--upgrade' to not upgrade pinned requirements with generic ones
- pip install -r requirements.txt
- pip list


script:
# Run Tests
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat travis-ci; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_tests.sh travis-ci; fi

# Run Linting
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_linters.bat; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_linters.sh; fi

# Run Package Safety Checks
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/check_package_safety_bare.bat; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/check_package_safety.sh; fi

after_success:
- codecov
